### ISSUE TITLE
Upgrade to latest from Odoo

### ISSUE THREAD

**Issue by euroblaze** [minhng92/odoo-18-docker-compose#1]
Hello @minhng92,

managed to install the newest v18 and all looks good.
`postgresql` database and the `odoo-server.log` file installed on the host, which is awesome!

We are doing some development now.

Question:
- How is it possible to upgrade Odoo core on a regular basis, as Odoo team fixes bugs etc.

Thanks, Ach

**Comment by minhng92** [comment]
Hi @euroblaze , To upgrade Odoo core, down the running containers, remove the current Odoo docker image and pull the new one.
```bash
docker-compose down
docker rmi odoo:18
docker-compose up -d               # this will pull the latest build of the image odoo:18
```

**Comment by euroblaze** [comment]
Thank you @minhng92 !

If anyone sees this error:
```
v18e@v17:~$ sudo docker rmi odoo:18
Error response from daemon: conflict: unable to remove repository reference "odoo:18" (must force) - container 72adcb76dee9 is using its referenced image f61b2a735432
```

Try following the below steps:

```
v18e@v17:~$ sudo docker stop 72adcb76dee9
v18e@v17:~$ sudo docker rm 72adcb76dee9
v18e@v17:~$ sudo docker rmi -f odoo:18
```
Output..
```
Untagged: odoo:18
Untagged: odoo@sha256:27d158dc157b43c9521f287ab0a040ebfecec75930b3e0a1d6af5fa9add63d59
Deleted: sha256:f61b2a73543257c065a7972b5280a4c659bf14846ad877ef3be9b112fb43502d
```

**Comment by minhng92** [comment]
Great! Thank you @euroblaze for your note.
