### ISSUE TITLE
Permissions are aweful

### ISSUE THREAD

**Issue by euroblaze** [minhng92/odoo-18-docker-compose#2]
Installing with `run.sh`, the permissions of all files and folders is set to 777.
This exposes the Odoo installation totally to security attacks.
And all files and folders are owned by `root`!

Couldn't `run.sh` `chmod` the directories before exiting?

![image](https://github.com/user-attachments/assets/694d6942-30d4-4f64-9a51-25ba0a169ebe)

---

Please take a pistol and shoot me in the head. 
Then all customers one by one.

---

```
find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;
```

**Comment by minhng92** [comment]
Hi @euroblaze , I just set the lowest security mode for all files to avoid issues related to permissions.

**Comment by euroblaze** [comment]
> I just set the lowest security mode for all files to avoid issues related to permissions.

Yes but they cannot be left like that.
Everything is exposed with 777, pants down!

Can the above `find` commands be incorporated?

In addition, one recommendation would be to install into a `/home/odoo18` (or similar) folder.

It is important for us programmers and ERP admins to think about security.

**Comment by Meursault667** [comment]
> ```
> find . -type f -exec chmod 644 {} \;
> find . -type d -exec chmod 755 {} \;
> ```

works great, I added for the `odoo-one` folder

```
sudo chown -R my-username /home/my-username/odoo-one
```

Nevertheless, thank you @minhng92 & @euroblaze . This safed my weekend.

**Comment by galexbh** [comment]
I believe that euroblaze is right and it should not be left exposed like this and the change would be simple:


```
#!/bin/bash
DESTINATION=$1
PORT=$2
CHAT=$3

# Clone Odoo directory
git clone --depth=1 https://github.com/minhng92/odoo-18-docker-compose $DESTINATION
rm -rf $DESTINATION/.git

# Create PostgreSQL directory
mkdir -p $DESTINATION/postgresql

# Change ownership to current user and set restrictive permissions for security
sudo chown -R $USER:$USER $DESTINATION
sudo chmod -R 700 $DESTINATION  # Only the user has access

# System configuration
if grep -qF "fs.inotify.max_user_watches" /etc/sysctl.conf; then 
    echo $(grep -F "fs.inotify.max_user_watches" /etc/sysctl.conf)
else 
    echo "fs.inotify.max_user_watches = 524288" | sudo tee -a /etc/sysctl.conf
fi
sudo sysctl -p

# Set ports in docker-compose.yml
sed -i 's/10018/'$PORT'/g' $DESTINATION/docker-compose.yml
sed -i 's/20018/'$CHAT'/g' $DESTINATION/docker-compose.yml

# Set file and directory permissions after installation
find $DESTINATION -type f -exec chmod 644 {} \;
find $DESTINATION -type d -exec chmod 755 {} \;

# Run Odoo
docker-compose -f $DESTINATION/docker-compose.yml up -d

echo "Odoo started at http://localhost:$PORT | Master Password: minhng.info | Live chat port: $CHAT"

```

**Comment by minhng92** [comment]
Thank you for your contributions: @euroblaze, @Meursault667, and galexbh.
I updated the permissions in `run.sh` in commit 0b7438f, following @galexbh 's script.
I hope it fixes the security risk associated with running the script.

**Comment by minhng92** [comment]
The older repositories, such as `odoo-17-docker-compose` and earlier versions, should be updated as well. I'll do it soon.
